"""PostgreSQL repository layer for RegLens HK MVP-RC2."""

from __future__ import annotations

from .annotations import (
    AnnotationError,
    get_annotation_by_decision,
    get_annotation_by_external_ref,
    list_annotations_for_decisions,
    upsert_annotation,
)
from .audit import insert_audit_event
from .conn import connect, transaction
from .decisions import (
    DECISION_NAMESPACE,
    DecisionError,
    decision_id_for,
    get_decision,
    link_document_version,
    public_slug_from_external_ref,
    upsert_decision,
)
from .documents import (
    DocumentError,
    insert_acquisition,
    insert_document_version,
    upsert_blob,
    upsert_document,
)
from .extractions import (
    ExtractionError,
    insert_extracted_proposition,
    insert_extraction_run,
    insert_proposition_evidence,
    insert_proposition_relation,
    persist_extraction_bundle,
    upsert_document_span,
)
from .releases import (
    APPROVED_STATUS,
    ReleaseRepoError,
    add_release_item,
    approve_and_build_release,
    create_draft_release,
    get_release,
    list_release_items,
    mark_release_published,
    update_item_artifact_hash,
    validate_release,
)
from .reviews import (
    ReviewError,
    RevisionConflictError,
    accept_or_edit,
    add_review,
    create_revision,
    list_pending,
)
from .search import FtsHit, SearchError, search, search_accepted_revisions
from .users import (
    AuthError,
    create_session,
    create_user,
    hash_password,
    hash_session_token,
    lookup_session,
    revoke_session,
    verify_password,
    verify_user_password,
)

__all__ = [
    "APPROVED_STATUS",
    "AnnotationError",
    "AuthError",
    "DECISION_NAMESPACE",
    "DecisionError",
    "DocumentError",
    "ExtractionError",
    "FtsHit",
    "ReleaseRepoError",
    "ReviewError",
    "RevisionConflictError",
    "SearchError",
    "accept_or_edit",
    "add_release_item",
    "add_review",
    "approve_and_build_release",
    "connect",
    "create_draft_release",
    "create_revision",
    "create_session",
    "create_user",
    "decision_id_for",
    "get_annotation_by_decision",
    "get_annotation_by_external_ref",
    "get_decision",
    "get_release",
    "hash_password",
    "hash_session_token",
    "insert_acquisition",
    "insert_audit_event",
    "insert_document_version",
    "insert_extracted_proposition",
    "insert_extraction_run",
    "insert_proposition_evidence",
    "insert_proposition_relation",
    "link_document_version",
    "list_annotations_for_decisions",
    "list_pending",
    "list_release_items",
    "lookup_session",
    "mark_release_published",
    "persist_extraction_bundle",
    "public_slug_from_external_ref",
    "revoke_session",
    "search",
    "search_accepted_revisions",
    "transaction",
    "update_item_artifact_hash",
    "upsert_annotation",
    "upsert_blob",
    "upsert_decision",
    "upsert_document",
    "upsert_document_span",
    "validate_release",
    "verify_password",
    "verify_user_password",
]
